Revert "WIP: hoping that a newer version of sphinx doesn't have the import error: 'ImportError: cannot import name 'entry_points' from 'importlib_metadata''"
This reverts commit 393383d199f37ba2846662cf24cd8dbaffd4f51f.

Updated minimum specs not compatible with python 3.9